#!/usr/bin/env bash


source utils


while read username usertags dl_media; do
	if [ "$dl_media" = 1 ]; then
		export DL_TWEET_MEDIA=1
	else
		export DL_TWEET_MEDIA=""
	fi
	echo "Scraping user: $username"
	user_id="$(get_user_id "$username")"
	
	while read usertag; do
		if [ "$TAGEM_MYSQL_CFG" ]; then
			mysql -e "INSERT INTO user2tag (user,tag) SELECT $user_id, t.id FROM tagem.tag t WHERE t.name=$(dblqt "$username") ON DUPLICATE KEY UPDATE tag=tag" twitter
		fi
	done < <(echo "$usertags" | sed 's/~~~/\n/g')
	
	while read tweet_id date time BST lt_username_gt text; do
		mysql -e "INSERT INTO post (id,user,t,text) VALUES ($tweet_id,$user_id,$(date -d "$date $time" +%s),$(dblqt "$text"))" twitter || continue # Skip 'duplicate key' errors, i.e. skip previously recorded
		
		sleep "$(shuf -i 2-5 -n 1).$(shuf -i 0-9 -n 1)"
		record_twitter_post "https://twitter.com/$username/status/$tweet_id" "$user_id" 1
		
		sleep "$(shuf -i 2-5 -n 1).$(shuf -i 0-9 -n 1)"
	done < <(twint -u "$username")
	
	mysql -e "UPDATE jobstr SET last_scraped=$(date +%s) WHERE username='$username'" twitter
done < <(mysql -r -s --disable-column-names -e "SELECT username, usertags, IFNULL(dl_media,0) FROM jobstr ORDER BY last_scraped ASC" twitter)
